version: '3.5'

services:
    caliper:
        platform: linux/amd64
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager --caliper-fabric-gateway-enabled
        privileged: true
        network_mode: "host"
        environment:
        - CALIPER_BIND_SUT=fabric:2.2
        - CALIPER_BENCHCONFIG=readDataBenchmark.yaml
        - CALIPER_NETWORKCONFIG=networkConfig.yaml
        volumes:
        - .:/hyperledger/caliper/workspace
        - ../test-network:/hyperledger/caliper/test-network
        - /var/run/docker.sock:/var/run/docker.sock