name: Caliper Test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: false

channels:
  - channelName: mychannel
    contracts:
      - id: health-contract

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "bgihr"
          clientPrivateKey:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/bgihr@org1.example.com/msp/keystore/fb444d050ee6bb328ac67448f4156f2097f23de91e208b7f2d947759fe5d5c05_sk"
          clientSignedCert:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/bgihr@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true